// export roles

const {
  EntityTypes,
  VendorTiers,
  VendorStatusCode,
  VendorApplicationStatus,
  TournamentApplicationStatus,
  TotalTurnover,
  TournamentTier,
  steps,
  vendor,
  entityType,
  stepLabels,
} = require("./enum/common");
const { Tasks } = require("./role-permissions/roles");
const { Validations } = require("./validations/validations");
const {
  emailError,
  dateOfBirthError,
  firstNameError,
  lastNameError,
  designationError,
  phoneError,
  companyNameError,
    companyMarketNameError,
    countryError,
    stateError,
    cityError,
    companyEmailError,
    comapnyPhoneError,
    websiteError,
    logoError,
    companyBioError,
    legalNameError,
    entityTypeError,
    panError,
    gstError,
    incorporationCertificateError,
    incorporationDateError
} = require("./enum/validationErrors");

module.exports = {
  Tasks,
  EntityTypes,
  VendorTiers,
  VendorStatusCode,
  VendorApplicationStatus,
  TournamentApplicationStatus,
  TotalTurnover,
  TournamentTier,
  Validations,
  steps,
  stepLabels,
  vendor,
  entityType,
  emailError,
  dateOfBirthError,
  firstNameError,
  lastNameError,
  designationError,
  phoneError,
  companyNameError,
  companyMarketNameError,
  countryError,
  stateError,
  cityError,
  companyEmailError,
  comapnyPhoneError,
  websiteError,
  logoError,
  companyBioError,
  legalNameError,
  entityTypeError,
  panError,
  gstError,
  incorporationCertificateError,
  incorporationDateError
};
